"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-rj#rxh#j_80o7b_#7$ll!v0$q9(@lsw%+c(!e$wj&45#mvziaj',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# В контейнере Django отвечает не на localhost, а на имя сервиса,
# поэтому список хостов задаётся переменной окружения
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                    # DRF
    'rest_framework_simplejwt',          # JWT-Authentifizierung
    'drf_spectacular',                   # OpenAPI-Dokumentation
    'django_filters',                    # Filter für DRF
    'users',                             # User-App
    'lms',                               # Course + Lesson
]

# DRF: аутентификация, права и фильтры на уровне всего проекта.
# По умолчанию каждый эндпоинт закрыт — доступ только с JWT-токеном.
# Открытые эндпоинты (регистрация, получение токена) объявляют AllowAny явно.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Настройки генератора OpenAPI-документации
SPECTACULAR_SETTINGS = {
    'TITLE': 'LMS API',
    'DESCRIPTION': (
        'API учебной платформы: курсы, уроки, подписки, '
        'платежи через Stripe и разграничение прав доступа.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'TAGS': [
        {'name': 'auth', 'description': 'Регистрация и JWT-токены'},
        {'name': 'users', 'description': 'Пользователи и профили'},
        {'name': 'courses', 'description': 'Курсы'},
        {'name': 'lessons', 'description': 'Уроки'},
        {'name': 'subscriptions', 'description': 'Подписки на обновления курсов'},
        {'name': 'payments', 'description': 'Платежи и оплата через Stripe'},
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# PostgreSQL вместо SQLite: SQLite — это файл, и он не переживает
# ни пересоздание контейнера, ни обращение из нескольких сервисов сразу.
# Параметры подключения приходят из .env, хост — имя сервиса из compose.
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('POSTGRES_DB', 'lms'),
        'USER': os.getenv('POSTGRES_USER', 'lms'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'lms'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Куда collectstatic складывает файлы. В контейнере этот каталог
# смонтирован томом, иначе статика админки пропадала бы при пересборке.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# По умолчанию письма печатаются в консоль — для разработки этого достаточно.
# Чтобы слать по-настоящему, задайте в .env EMAIL_BACKEND и параметры SMTP.

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'lms@example.com')

AUTH_USER_MODEL = 'users.User'  # Custom User-Modell

# Stripe
# Тестовый ключ берётся из .env, в репозиторий не попадает.
STRIPE_API_KEY = os.getenv('STRIPE_API_KEY', '')
# Куда Stripe вернёт пользователя после оплаты
STRIPE_SUCCESS_URL = os.getenv('STRIPE_SUCCESS_URL', 'http://127.0.0.1:8000/api/payments/success/')
STRIPE_CANCEL_URL = os.getenv('STRIPE_CANCEL_URL', 'http://127.0.0.1:8000/api/payments/cancel/')

# Celery
# Брокер и бэкенд результатов — Redis, параметры подключения из .env.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Таймзона Celery обязана совпадать с таймзоной Django,
# иначе периодические задачи запускаются не в то время.
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ

# Расписание периодических задач для celery-beat
CELERY_BEAT_SCHEDULE = {
    'block-inactive-users-every-night': {
        'task': 'users.tasks.block_inactive_users',
        # Каждый день в 03:00 по TIME_ZONE проекта
        'schedule': crontab(hour=3, minute=0),
    },
}

# Сколько пользователь может не заходить, прежде чем его заблокируют
INACTIVITY_DAYS_LIMIT = int(os.getenv('INACTIVITY_DAYS_LIMIT', 30))

# Как часто максимум уведомлять подписчиков об обновлении одного курса
COURSE_UPDATE_NOTIFY_HOURS = int(os.getenv('COURSE_UPDATE_NOTIFY_HOURS', 4))
